### ISSUE TITLE
NSMBDS music playback is wrong - too much reverb and square waves are too quiet

### ISSUE THREAD

**Issue by Alzter** [vgmtrans/vgmtrans#389]
### Environment details

* Operating System+version: **Windows 10 Home**
* VGMTrans version: **vgmtrans-preview-v1.1-windows_x64**
* Game ROM/music dump name and sha256: **New Super Mario Bros. (Europe)**, **I don't know where to find the SHA256**

### Describe the bug

When attempting to play music from New Super Mario Bros. DS in VGMtrans on the latest version, there is a reverb filter applied over all of the instruments. This differs from how the music sounds on the actual DS hardware and in my opinion it sounds muddier and worse. Also, the square wave instruments are noticeably quieter than they should be.

### Steps to reproduce

1. Open VGMtrans
2. Open the New Super Mario Bros DS ROM
3. Attempt to play a music track from the game in VGMtrans

### Expected behaviour

The music from New Super Mario Bros, and other DS games by extension, should not have a reverb filter put on all of the instruments, and the square wave channels should have the correct volume.

**Comment by sykhro** [comment]
The reverb part should be fixed in the latest master, which you can download from [here](https://nightly.link/vgmtrans/vgmtrans/workflows/build/master). As for the PSG instruments, I'll check that we're outputting them at 0dbfs

**Comment by Bonboon229** [comment]
Can confirm the latest nightly does NOT fix the reverb issues at all.

**Comment by sykhro** [comment]
Thanks for testing, will look into it

**Comment by CodingPigFromTheBushes** [comment]
Kirby Squeak Squad seems to have the same problem with all samples having excessive amounts of reverb.

**Comment by Bonboon229** [comment]
Can again confirm this issue, this also affects all Kirby DS Games

**Comment by benduckwdesign** [comment]
Happens with Pokemon too, I built it from master just two days ago
